title: My very 1st GH Page
author: Leonardo Kojima
email: leonardo.kojima@comdinheiro.com.br
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
  Editing my config.yml

# social links
#twitter_username: your-twitter-handle # dont have one
github_username:  leonardo-kojima-cmd # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
